services:
  godis:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '6379:6379'
    volumes:
      - .:/app
    environment:
      - GODIS_PORT=6379
      - GODIS_CONFIG_PATH=./example/config.yml
